RelitRaysPerProbe: 400
DefaultRelitHysteresis: 0.8000005
MinHysteresis: 0.3
MaxHysteresis: 0.8000005
RelitVolumesBudget: 2
ProbeIlluminanceDataRes:
  - 6
  - 6
ProbeHitDistanceDataRes:
  - 14
  - 14
LodsConfigs:
  - VolumeResolution:
      - 24
      - 24
      - 12
    RelitZoneResolution:
      - 12
      - 12
      - 12
    ProbesSpacing:
      - 1.5
      - 1.5
      - 1.5
    RelitPriority: 2.5
    ForwardAlignment: 0.5
    HeightAlignment: 0.2
  - VolumeResolution:
      - 36
      - 36
      - 12
    RelitZoneResolution:
      - 12
      - 12
      - 12
    ProbesSpacing:
      - 4
      - 4
      - 4
    RelitPriority: 1
    ForwardAlignment: 0.5
    HeightAlignment: 0.1
  - VolumeResolution:
      - 36
      - 36
      - 12
    RelitZoneResolution:
      - 12
      - 12
      - 12
    ProbesSpacing:
      - 8.000001
      - 8.000001
      - 8.000001
    RelitPriority: 0.5
    ForwardAlignment: 0
    HeightAlignment: 0.1
  - VolumeResolution:
      - 24
      - 24
      - 24
    RelitZoneResolution:
      - 12
      - 12
      - 12
    ProbesSpacing:
      - 1024
      - 1024
      - 1024
    RelitPriority: 0.5
    ForwardAlignment: 0
    HeightAlignment: 0