LocalRelitRaysNumPerProbe: 400
GlobalRelitRaysPerProbe: 300
GlobalRelitHysteresis: 0.80000031
LocalRelitHysteresis: 0.700000167
MinHysteresis: 0.300000012
MaxHysteresis: 0.850000024
LocalRelitProbeGridSize:
  - 6
  - 6
  - 6
RelitVolumesBudget: 3
ProbeIlluminanceDataRes:
  - 6
  - 6
ProbeHitDistanceDataRes:
  - 16
  - 16
Lod0VolumeResolution:
  - 12
  - 12
  - 12
Lod0ProbesSpacing:
  - 1.5
  - 1.5
  - 1.5
Lod1VolumeResolution:
  - 12
  - 12
  - 10
Lod1ProbesSpacing:
  - 2.4000001
  - 2.4000001
  - 2.4000001
Lod1VolumesMinHeight: -1.79999995