RelitRaysPerProbe: 400
DefaultRelitHysteresis: 0.800000489
MinHysteresis: 0.300000012
MaxHysteresis: 0.800000489
RelitVolumesBudget: 2
ProbeIlluminanceDataRes:
  - 6
  - 6
ProbeHitDistanceDataRes:
  - 14
  - 14
LodsConfigs:
  - VolumeResolution:
      - 24
      - 24
      - 12
    RelitZoneResolution:
      - 12
      - 12
      - 12
    ProbesSpacing:
      - 1.10000002
      - 1.10000002
      - 1.10000002
    RelitPriority: 2.5
    ForwardAlignment: 0.5
    HeightAlignment: 0.200000003
  - VolumeResolution:
      - 36
      - 36
      - 12
    RelitZoneResolution:
      - 12
      - 12
      - 12
    ProbesSpacing:
      - 2.4000001
      - 2.4000001
      - 2.4000001
    RelitPriority: 1
    ForwardAlignment: 0.5
    HeightAlignment: 0.100000001
  - VolumeResolution:
      - 36
      - 36
      - 12
    RelitZoneResolution:
      - 12
      - 12
      - 12
    ProbesSpacing:
      - 3.700001
      - 3.700001
      - 3.700001
    RelitPriority: 0.5
    ForwardAlignment: 0
    HeightAlignment: 0.100000001