Environment: 1
GenerateDebugInfo: true
CompileWithDebugs: true
UseCompiledShadersCache: true
CacheSeparateSpvFile: false
ShadersPath: Shaders
ShadersCachePath: Saved/Shaders/Cache
ErrorLogsPath: Saved/Shaders/Errors