#ifndef SPT_GEOMETRY_DEFINES_HLSLI
#define SPT_GEOMETRY_DEFINES_HLSLI

#define SPT_GEOMETRY_VISIBLE_GEOMETRY_PASS     0
#define SPT_GEOMETRY_DISOCCLUDED_GEOMETRY_PASS 1
#define SPT_GEOMETRY_DISOCCLUDED_MESHLETS_PASS 2

#endif // SPT_GEOMETRY_DEFINES_HLSLI
