#ifndef GEOMETRY_COMMON_H
#define GEOMETRY_COMMON_H

#define SPT_GEOMETRY_VISIBLE_GEOMETRY_PASS     0
#define SPT_GEOMETRY_DISOCCLUDED_GEOMETRY_PASS 1
#define SPT_GEOMETRY_DISOCCLUDED_MESHLETS_PASS 2

#endif // GEOMETRY_COMMON_H