StartProjectsType(EProjectType.Engine)

IncludeProject("SculptorCore")
IncludeProject("Math")
IncludeProject("Profiler")
IncludeProject("SculptorLib")
IncludeProject("RHICore")
IncludeProject("VulkanRHI")
IncludeProject("RHI")
IncludeProject("Window")